### ISSUE TITLE
"Event Upgrading" documentation

### ISSUE THREAD

**Issue by malclear** [Akkatecture/Documentation#108]
In the "Event Upgrading" documentation, the generic type parameters are reversed. 
`IUpcast<ProductAddedEventV2, ProductAddedEvent>`
should be...
`IUpcast<ProductAddedEvent, ProductAddedEventV2>`

**Comment by Lutando** [comment]
Yes :) I just fixed it thanks!

**Comment by Lutando** [comment]
Fixed on https://github.com/Akkatecture/Documentation/commit/687faae92f3544ffba09667ccec77bd8b12fd0d6
